### ISSUE TITLE
의견

### ISSUE THREAD

**Issue by hynkang** [Jackson-Kang/Pytorch-Diffusion-Model-Tutorial#1]
DDPM이 기존의 다른 generative model에 비해 어떤 점이 확실히 좋은지
tutorial에 있는 예시로는 잘 안 보이는 것 같아요

**Comment by Jackson-Kang** [comment]
현주님,, 살려주세요,,

**Comment by Jackson-Kang** [comment]
이슈 닫을게요? ㅋㅋㅋ
